export const questions = [
  {
    id: 1,
    type: "input",
    text: "What is common between Naruto and Trent Lane?",
    correctAnswer: ["Uzumaki", "Spiral"],
    image: "../../bubbles/trent.gif",
  },
  {
    id: 2,
    type: "input",
    text: "Which train heads to Tokyo station?",
    correctAnswer: "Shinkansen 0",
    image: "../../bubbles/shinkansen.gif",
  },
  {
    id: 3,
    type: "input",
    text: "Which number is missing: Skankhunt__?",
    correctAnswer: "42",
    image: "../../bubbles/skank.gif",
  },
  {
    id: 4,
    type: "input",
    text: "Name 1 of the detective Littlejohn's favourite songs",
    correctAnswer: ["My Way", "This is Halloween"],
    image: "../../bubbles/song.gif",
  },
  // {
  //   id: 5,
  //   type: "input",
  //   text: "Which number is missing: Skankhunt__?",
  //   correctAnswer: "Shinkansen 0",
  //   // image: "../../bubbles/shinkansen.gif",
  // },
  // {
  //   id: 6,
  //   type: "input",
  //   text: "Which number is missing: Skankhunt__?",
  //   correctAnswer: "Shinkansen 0",
  //   // image: "../../bubbles/shinkansen.gif",
  // },
  // {
  //   id: 7,
  //   type: "input",
  //   text: "Which number is missing: Skankhunt__?",
  //   correctAnswer: "Shinkansen 0",
  //   // image: "../../bubbles/shinkansen.gif",
  // },
];
