export const questions = [
  {
    id: 1,
    type: "input",
    text: "Hi there, young man. I feel something special about you",
    correctAnswer: ["Jack", "Jack Skellington"],
    image: "../../bubbles/intro1.png",
    alert: "Are you ready to rrrrrrrrrrumble?!",
  },
  {
    id: 2,
    type: "input",
    text: "How many fingers of milk should young mafioso drink?",
    correctAnswer: ["3", "Three"],
    image: "../../bubbles/milk1.png",
    alert: "🥛🥛🥛",
  },
  {
    id: 3,
    type: "input",
    text: "Which number is missing: Skankhunt__?",
    correctAnswer: ["42"],
    image: "../../bubbles/skank_stat.png",
    alert: "You're a fat wh0re",
  },
  {
    id: 4,
    type: "input",
    text: "The day before two days after the day before tomorrow is Saturday. What day is it today?",
    correctAnswer: ["Friday"],
    image: "../../bubbles/days_stat.png",
    alert: "Too bad it's not Friday today",
  },
  {
    id: 5,
    type: "input",
    text: "Which train heads to Tokyo station?",
    correctAnswer: ["Shinkansen 0"],
    image: "../../bubbles/shinkansen_stat.png",
    alert: "And they say it's useless to watch letsplays...",
  },
  {
    id: 6,
    type: "input",
    text: "There is a rope and a hat. What should be third: a soap, a chest, a book or a woman?",
    correctAnswer: ["chest", "the chest", "a chest"],
    image: "../../bubbles/rope.png",
    alert: "Alfred Hitchc0ck is proud of you",
  },
  {
    id: 7,
    type: "input",
    text: "What is common between Naruto and Trent Lane?",
    correctAnswer: ["Uzumaki", "Spiral"],
    image: "../../bubbles/trent_stat.png",
    alert: "ヘンタイ大好き",
  },
  {
    id: 8,
    type: "input",
    text: "I am the beginning of everything, the end of time and space, the beginning of every end, and the end of every place. What am I?",
    correctAnswer: ["The letter E", "Letter E", "E"],
    image: "../../bubbles/e_stat.png",
    alert:
      "There are four seasons, four horsemen of the apocalypse and four letters in your name. Is there a pattern?",
  },
  {
    id: 9,
    type: "input",
    text: "jmrh xli vih erh csy ampp kix",
    correctAnswer: ["find the red and you will get"],
    image: "../../bubbles/cipher_stat.png",
    alert: "I respect that you know the encryption basics. Now find the red.",
  },

  {
    id: 10,
    type: "input",
    text: "Name 1 of the detective Littlejohn's favourite songs",
    correctAnswer: [
      "My Way",
      "This is Halloween",
      "Twist",
      "New magic wand",
      "That's Life",
    ],
    image: "../../bubbles/song_stat.png",
    alert: "Breaking the 4th wall, huh, detective?",
  },
  {
    id: 11,
    type: "input",
    text: "What goes on four feet in the morning, two feet in midday, and three feet in the evening?",
    correctAnswer: ["Man", "Human", "Person"],
    image: "../../bubbles/sphinx_stat.png",
    alert: "Congratulations, you killed the sphinx!",
  },
  {
    id: 12,
    type: "button",
    text: "Well, I'm satisfied with your performance. Look for more questions and you'll get the answers, good luck!",
    correctAnswer: [
      "What questions?",
      "What questions",
      "good luck",
      "goodbye",
    ],
    image: "../../bubbles/fin.png",
    alert: "Congratulations, you killed the sphinx!",
  },
];
