export const questions = [
  {
    id: 1,
    type: "input",
    text: "What is common between Naruto and Trent Lane?",
    correctAnswer: ["Uzumaki", "Spiral"],
    image: "../../bubbles/trent.gif",
  },
  {
    id: 2,
    type: "input",
    text: "Which train heads to Tokyo station?",
    correctAnswer: ["Shinkansen 0"],
    image: "../../bubbles/shinkansen.gif",
  },
  {
    id: 3,
    type: "input",
    text: "Which number is missing: Skankhunt__?",
    correctAnswer: ["42"],
    image: "../../bubbles/skank.gif",
  },
  {
    id: 4,
    type: "input",
    text: "Name 1 of the detective Littlejohn's favourite songs",
    correctAnswer: ["My Way", "This is Halloween", "Twist"],
    image: "../../bubbles/song.gif",
  },
  {
    id: 5,
    type: "input",
    text: "I am the beginning of everything, the end of time and space, the beginning of every end, and the end of every place. What am I?",
    correctAnswer: ["The letter E", "Letter E", "E"],
    image: "../../bubbles/e.gif",
  },
  {
    id: 6,
    type: "input",
    text: "The day before two days after the day before tomorrow is Saturday. What day is it today?",
    correctAnswer: ["Friday"],
    image: "../../bubbles/days.gif",
  },
  {
    id: 7,
    type: "input",
    text: "What goes on four feet in the morning, two feet in midday, and three feet in the evening?",
    correctAnswer: ["Man", "Human", "Person"],
    image: "../../bubbles/sphinx.gif",
  },
];
